### ISSUE TITLE
License is not open-source

### ISSUE THREAD

**Issue by joepie91** [IonicaBizau/regex-escape.js#4]
The "KINDLY license" violates point 6 of the [Open Source Definition](http://opensource.org/osd-annotated), and is therefore not an open-source license. The culprit is the following section:

```
  - if you want to use this software or include parts of its code in a
   closed-source or commercial project you should kindly ask the
   author (via a private message or email) and get a positive answer
```

... which also isn't necessary if your intention is to prevent automatic usability in closed-source software, because you can grant additional licenses on an individual basis _anyway_, eg. when using the GPL.

Licenses that prohibit commercial use (not the same as 'closed-source'!) are not open-source either way, as they are always in violation of point 6.

I'd also recommend having a read through [this article](http://cryto.net/~joepie91/blog/2013/03/21/licensing-for-beginners/), which explains the issue with writing custom licenses, and provides a comparison of the most common licenses.

Unfortunately, with its current license, I can't use this module in my project - with it being an open-source project, all of its dependencies must also be redistributable under an open-source license.

**Comment by IonicaBizau** [comment]
Hmm, good points here! I didn't say this is open-source software, but I realize it wasn't a smart move. :smile: 

After some months after creating and using this license I realize it didn't make the things simpler. I will take care of this and will switch the libraries to use the MIT license and the projects that cannot be used as dependencies will still use The KINDLY License.

> Unfortunately, with its current license, I can't use this module in my project - with it being an open-source project, all of its dependencies must also be redistributable under an open-source license.

That being said, you can start using it in your project without worries, and people can use  your app around the world (interpret it as my _yes_), and soon I will switch back to use MIT license. :grin: 

I do love open-source and I see that this license actually complicated the things. :sparkling_heart:

**Comment by joepie91** [comment]
Good to hear :)

**Comment by IonicaBizau** [comment]
@joepie91 End of this week I hope to have this issue fixed (at least for this repository). :sparkle: Thanks for feedback, btw. :smile:

**Comment by IonicaBizau** [comment]
Just released **`3.2.0`** which is open-source. So, feel free to use and spread it to the world. :tada:

**Comment by joepie91** [comment]
Nice to see it resolved so quickly, but I think you forgot the `LICENSE` file :)

**Comment by IonicaBizau** [comment]
@joepie91 OooooOOOooo! Thanks!!! :cake: 

:ship: **`3.3.0`**

**Comment by IonicaBizau** [comment]
@joepie91 I launched http://showalicense.com/ and in the next days I will update the projects to use the MIT license and links to the MIT license. :sparkles:

**Comment by IonicaBizau** [comment]
@joepie91 Last week I relicensed _all_ my projects (back) to MIT. :smile: :tada:

**Comment by joepie91** [comment]
Good to see things progressing! :)

**Comment by IonicaBizau** [comment]
@joepie91 Here is more info related to this: https://github.com/IonicaBizau/youtube-api/issues/47#issuecomment-162421847 :memo:
